---
- name: use the datastax enterprise repository
  apt_repository: repo="deb http://{{ dse_username }}:{{ dse_password }}@debian.datastax.com/enterprise stable main" state=present
  
- name: add repository key
  apt_key: url=https://debian.datastax.com/debian/repo_key state=present

- name: install DSE packages
  apt: pkg=dse-full state=installed
  notify:
    - restart dse

- name: configure cassandra
  template: src=cassandra.yml.j2 dest=/etc/dse/cassandra/cassandra.yaml 
  tags: datastax
  notify:
    - restart dse


 
