---
#Provision some APP instances:
hosts: localhost
gather_facts: False
tasks:
- name: Launch instances
  local_action: ec2 
    keypair={{ keypair }} 
    security_group={{ security_group }} 
    instance_type={{ instance_type }} 
    image={{ image }} 
    region={{ region }} 
    vpc_subnet_id={{ vpcnetid }} 
    instance_tags='{"app":"all"}' 
    wait=true 
    count={{ appcount }}
  register: ec2

- name: Add new instance to host group
  local_action: add_host hostname={{ item.public_ip }} groupname=app
  with_items: ec2.instances

- name: Wait for SSH to come up
  local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances

- name: Configure instance(s)
  hosts: app
  sudo: true
  gather_facts: true
  roles:
    - common
    - java
    - immutant
    - immutant-app