---
###General EC2 Below

ec2_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
ec2_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
ec2_region: us-east-1
ec2_zone: us-east-1a
ec2_image: ami-9c78c0f5
ec2_instance_type: m1.large
ec2_keypair: anstest
ec2_security_group: default
ec2_app_instance_count: 2
ec2_proxy_instance_count: 2
ec2_db_instance_count: 2
aws_creds:
  AWS_DEFAULT_REGION: "{{ ec2_region }}"
  AWS_ACCESS_KEY: "{{ ec2_access_key }}"
  AWS_SECRET_KEY: "{{ ec2_secret_key }}"

###Non-Infrastructure here:

cluster_name: evaluation
cassandra_cluster: "{{ cluster_name }}"
cassandra_listen_address: 127.0.0.1
cassandra_native_port: 19042

datomic_listen_address: localhost
datomic_protocol: dev
datomic_version: 0.9.4384
datomic_type: datomic-pro
datomic_filename: "{{ datomic_type }}-{{datomic_version }}"

clojure_app_user: "deploy"
clojure_app_name: "orchestra"
clojure_app_dir: "/var/lib/swb-orchestra"
clojure_app_root: "/orchestra"
clojure_app_git_repo: "ssh://git@github.com/vitalreactor/switchboard"
clojure_app_git_version: "{{ orchestra_commit }}"
clojure_app_profile: "{{ orchestra_profiles }}"
clojure_app_args: ""
clojure_app_log_dir: "/var/log/clojure"

#For lein in app-immutant-deploy:
lein_dir: /usr/local/bin

immutant_version: 1.1.1
immutant_profiles: "prod"

switchboard_version: HEAD
switchboard_config: /var/admin/files/switchboard_eval.edn
switchboard_client_url: http://eval.orchestra.md
switchboard_vhost: eval.swb.io
switchboard_address: localhost
switchboard_port: 8080
switchboard_context: api
switchboard_profiles: dev
switchboard_app: "1"

orchestra_commit: HEAD
orchestra_profiles: user,dev
orchestra_vhost: eval.orchestra.md
orchestra_address: localhost
orchestra_port: 3000

# Datastax repository credentials
dse_username: 
dse_password: 

# Datomic license key (PE)
datomic_license: 

java_download: http://download.oracle.com/otn-pub/java/jdk/7u45-b18/jdk-7u45-linux-x64.tar.gz
java_name: jdk1.7.0_45
java_download_folder: /usr/src
java_archive: "{{download_folder}}/{{java_name}}.tar.gz"
java_folder: /usr/lib/jvm
java_alias: java-7-oracle