## You must place a yml config in your .ssh location for this playbook task to run!

- name: gather facts from all hosts
  hosts: all:!localhost
  remote_user: ubuntu
  tasks: []

- name: Deploy Initial Configs Switchboard Orchestra Common
  hosts: tag_Name_{{environ|default('dev')}}_app
  remote_user: ubuntu
  #serial: 1
  sudo: true

  vars_files:
  - "{{ lookup('env', 'HOME') }}/.ssh/switchboard_vars.yml"

  roles:
  - common
  - java
  - app-deploy
