# PROXY: Ensure we have a local proxy ready to route requests
- name: Deploy Initial Configs Proxy Common
  hosts: tag_Name_{{environ|default('dev')}}_proxy
  remote_user: ubuntu
  sudo: true

  roles:
  - common

# PROXY: Ensure we have a local proxy ready to route requests
- name: Deploy Initial Configs Proxy
  hosts: tag_Name_{{environ|default('dev')}}_proxy
  remote_user: ubuntu
  sudo: true


  roles:
  - proxy-config
