---
# DATABASE: Ensure our database tier is running correctly
- name: Deploy Initial Configs DB
  hosts: tag_Name_{{environ|default('dev')}}_db_seed
  remote_user: ubuntu
  sudo: true



  pre_tasks:

  roles:
  - common
  - java

- name: Bring up Datomic transactor
  hosts: tag_Name_{{environ|default('dev')}}_db_seed
  remote_user: ubuntu
  sudo: true
  serial: 1

  vars_files:
  - "{{ lookup('env', 'HOME') }}/.ssh/switchboard_vars.yml"


  roles:
  - db-datomic

