---
- name: Gather facts from all hosts
  hosts: "tag_{{ environ|default('dev') }}_all_"
  remote_user: ubuntu
  sudo: true


  tasks:
  - name: Gather EC2-based facts
    ec2_facts:

  roles:
  - newrelic

