## You must place a yml config in your .ssh location for this playbook task to run!

- name: Gather facts from all hosts
  hosts: "{{ environ|default('dev') }}_all_"
  remote_user: ubuntu 

- name: Deploy Initial Configs Switchboard Orchestra Common
  hosts: tag_Name_{{environ|default('dev')}}_app
  remote_user: ubuntu
  serial: 1
  sudo: true

  vars_files:
  - "{{ lookup('env', 'HOME') }}/.ssh/switchboard_vars.yml"

  roles:
  - common
  - java
  - app-deploy
