---
#Provision some proxy instances:
hosts: localhost
gather_facts: False
vars_files:
  - vars/ec2.yml
tasks:
- name: Launch instances
  local_action: ec2 
    ec2_access_key="{{ ec2_access_key }}"
    ec2_secret_key="{{ ec2_secret_key }}"
    keypair={{ keypair }} 
    security_group={{ security_group }} 
    instance_type={{ instance_type }} 
    image={{ image }} 
    region={{ region }} 
    vpc_subnet_id={{ vpc.vpc_id }} 
    instance_tags='{"proxy":"all"}' 
    wait=true 
    count={{ proxcount }}
  register: ec2

- name: Add new instance to host group
  local_action: add_host hostname={{ item.public_ip }} groupname=proxy
  with_items: ec2.instances

- name: Wait for SSH to come up
  local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances

- name: Configure instance(s)
  hosts: proxy
  sudo: true
  gather_facts: true
  roles:
    - common
    - proxy