---
#Provision some proxy instances:
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
  - group_vars/all
  tasks:
  - name: Launch instances
    ec2: >
     access_key="{{ ec2_access_key }}"
     secret_key="{{ ec2_secret_key }}"
     keypair="{{ ec2_keypair }}"
     group="{{ ec2_group }}"
     type="{{ ec2_instance_type }}"
     image="{{ ec2_image }}"
     region="{{ ec2_region }}"
     instance_tags="{'name':'proxy', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}'}"
     count="{{ ec2_app_instance_count }}"
     wait=true
    register: ec2

  - name: Add new instance to host group
    local_action: add_host
      hostname="{{ item.public_ip }}"
      groupname=proxy
    with_items: ec2.instances

  - name: Wait for SSH to come up
    local_action: wait_for host={{ item.public_dns_name }}
      port=22 delay=60 timeout=320 state=started
    with_items: ec2.instances