---
##Testing playbook for individual roles
##This assumes VPC was created and instances are running.
- name: Gather facts
  hosts: tag_Name_dev_app
  remote_user: ubuntu
  vars_files:
  - vars/main.yml
  sudo: true
  tasks: []




  

- name: test the role.
  hosts: tag_Name_dev_app
  remote_user: ubuntu
  vars_files:
  - vars/main.yml
  - "{{ lookup('env', 'HOME') }}/.ssh/switchboard_vars.yml"


  roles:
  - app-deploy
 

# ##Testing playbook for individual roles
# ##This assumes VPC was created and instances are running.
# - name: Gather fact role test 2
#   hosts: tag_Name_dev_app
#   remote_user: ubuntu
#   sudo: true
#   vars_files:
#   - vars/main.yml

#   tasks: []

# - name: test the role 2.
#   hosts: tag_Name_dev_app
#   remote_user: ubuntu
#   sudo: true
#   vars_files:
#   - vars/main.yml

#   roles:
#   - app-clojure-config
